import type { Product } from './types';

const productDescription = "for the ones who feel deeply.\nsoft fabric, relaxed fit, everyday comfort.\nmade for slow days, late nights & honest hearts.";
const productDetails = {
  fit: 'unisex',
  fabric: 'soft cotton',
  feel: 'breathable, gentle on skin',
};

export const products: Product[] = [
  {
    id: '1',
    slug: 'dil-soft-intentions-clear-oversized-beige',
    quote: 'dil soft, intentions clear',
    fit: 'oversized',
    color: 'beige',
    price: 999,
    imageId: 'dil-soft-beige',
    description: productDescription,
    details: productDetails,
    collection: 'drop-01',
  },
  {
    id: '2',
    slug: 'thoda-pyar-more-peace-regular-white',
    quote: 'थोड़ा प्यार, more peace',
    fit: 'regular',
    color: 'white',
    price: 899,
    imageId: 'pyar-peace-white',
    description: productDescription,
    details: productDetails,
    collection: 'drop-01',
  },
  {
    id: '3',
    slug: 'healing-ho-rahi-hai-oversized-black',
    quote: 'healing हो रही है, slowly',
    fit: 'oversized',
    color: 'black',
    price: 1049,
    imageId: 'healing-black',
    description: productDescription,
    details: productDetails,
    collection: 'drop-01',
  },
  {
    id: '4',
    slug: 'bas-ehsaas-no-pressure-regular-beige',
    quote: 'bas ehsaas, no pressure',
    fit: 'regular',
    color: 'beige',
    price: 899,
    imageId: 'bas-ehsaas-beige',
    description: productDescription,
    details: productDetails,
    collection: 'drop-01',
  },
  {
    id: '5',
    slug: 'soft-hoon-but-i-stand-my-ground-oversized-white',
    quote: 'soft hoon, but I stand my ground',
    fit: 'oversized',
    color: 'white',
    price: 999,
    imageId: 'soft-hoon-white',
    description: productDescription,
    details: productDetails,
    collection: 'drop-01',
  },
  {
    id: '6',
    slug: 'dil-naram-hai-boundaries-strong-regular-black',
    quote: 'दिल नरम है, boundaries strong',
    fit: 'regular',
    color: 'black',
    price: 899,
    imageId: 'dil-naram-black',
    description: productDescription,
    details: productDetails,
    collection: 'drop-01',
  },
];
